[package]
name = "fuzzy-aho-corasick"
version = "0.3.6"
edition = "2024"
license = "MIT"
description = "Ahoâ€“Corasick automaton with fuzzy matching"
repository = "https://github.com/kakserpom/fuzzy-aho-corasick-rs"
[dependencies]
itertools = "0.14.0"
unicode-segmentation = "1.12"
[dev-dependencies]
criterion = "0.6"
[[bench]]
name = "benchmark"
harness = false
